// import { Injectable } from '@angular/core';

// @Injectable({
//   providedIn: 'root'
// })
import { ChangeDetectorRef, Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Language = 'en' | 'nso' | 'ts';

const translations = {
  en: {
        logo: "Ntirho",
        language: "English",
        languageOptionSepedi: "Sepedi",
        languageOptionEnglish: "English",
        signUp: "Sign Up",
        logIn: "Log In",
        logOut: "Log Out",
        heroTitle: "Find Jobs Near You",
        thaboStoryTitle: "Thabo's Story",
        thaboStory: "Consider Thabo, a recent graduate from a small village who finds that traditional platforms like LinkedIn aren’t tailored to his local context, leaving him with few opportunities.",
        footerContact: "Contact Us",
        footerPrivacy: "Privacy Policy",
        footerTraining: "Training Resources",
        footerRights: "Ntirho. All rights reserved.",
        postJobTitle: "Post a New Job",
        jobTitleLabel: "Job Title",
        jobTitlePlaceholder: "e.g., General Worker",
        companyLabel: "Company",
        companyPlaceholder: "e.g., BuildIt Polokwane",
        locationLabel: "Location or Job Title",
        locationPlaceholder: "e.g., Polokwane or Developer",
        descriptionLabel: "Job Description",
        descriptionPlaceholder: "Describe the job responsibilities and requirements.",
        skillsLabel: "Required Skills",
        skillsPlaceholder: "Select required skills",
        skillsDescription: "Select all skills required for this job.",
        skillsDescriptionProfile: "Select all skills that apply to you.",
        postJobButton: "Post Job",
        postJobFooterLink: "Post a Job",
        browseJobsTitle: "Browse Job Opportunities",
        browseJobsSubtitle: "Find work that matches your skills in your area.",
        filterBySkillPlaceholder: "Filter by skill",
        allSkills: "All Skills",
        clearFilters: "Clear Filters",
        noJobsFoundTitle: "No Jobs Found",
        noJobsFoundSubtitle: "Try adjusting your filters to find more opportunities.",
        viewDetails: "View Details",
        yourJobMatchesTitle: "Your Job Matches",
        welcomeBack: "Welcome back",
        yourJobMatchesSubtitle: "Here are jobs tailored for you.",
        findingJobsLoading: "Finding the best jobs for you...",
        errorOccurredTitle: "An Error Occurred",
        tryAgain: "Try Again",
        noMatchesFoundTitle: "No Matches Found",
        noMatchesFoundSubtitle: "We couldn't find any jobs matching your skills right now. Try updating your profile.",
        matchScore: "Match Score",
        matchedSkills: "Matched Skills",
        editProfile: "Edit Profile",
        editProfileTitle: "Edit Your Profile",
        editProfileDescription: "Make changes to your profile here. Click save when you're done.",
        mySkills: "My Skills",
        myInterests: "My Interests",
        createAccountTitle: "Create Your Account",
        myAccount: "My Account",
        profile: "Profile",
        myMatches: "My Matches",
        findAJob: "Find a Job",
        jobPostedSuccessTitle: "Job Posted Successfully",
        jobPostedSuccessDesc: "The new job has been added to the listings.",
        jobPostedErrorTitle: "Posting Failed",
        jobPostedErrorDesc: "An error occurred while posting the job. Please try again.",
        searchSkillsPlaceholder: "Search skills...",
        noSkillsFound: "No skills found.",
        magicLinkSentTitle: "Magic Link Sent!",
        magicLinkSentDesc: "You are now being logged in.",
        loginSuccessTitle: "Login Successful",
        loginFailedTitle: "Login Failed",
        loginFailedDesc: "Could not send magic link. Please try again.",
        magicLinkPrompt: "Enter your email to receive a magic link to sign in.",
        emailPlaceholder: "Enter your email",
        sendMagicLink: "Login",
        profileUpdateSuccessTitle: "Profile Updated",
        profileUpdateSuccessDesc: "Your changes have been saved successfully.",
        profileUpdateErrorTitle: "Update Failed",
        profileUpdateErrorDesc: "An error occurred while updating your profile. Please try again.",
        nameLabel: "Name",
        namePlaceholder: "Enter your name",
        saveChanges: "Save Changes",
        registrationSuccessTitle: "Registration Successful",
        registrationSuccessDesc: "Your account has been created.",
        registrationFailedTitle: "Registration Failed",
        registrationFailedDesc: "An error occurred during registration. Please try again.",
        emailLabel: "Email",
        submit: "Submit",
        voiceSearchListening: "Listening...",
        voiceSearchSpeakNow: "Speak now to search with your voice.",
        voiceSearchComplete: "Search Complete!",
        voiceSearchProcessed: "Your voice search has been processed.",
        voiceSearchFailed: "Voice Search Failed",
        voiceSearchFailedDesc: "Could not process your voice input. Please try again.",
        voiceSearchTitle: "Search with your voice",
        voiceSearchDescription: "Can't type? No problem. Press the button and tell us what job you're looking for in Sepedi.",
        youSaidSepedi: "You said (Sepedi):",
        weUnderstoodEnglish: "We understood (English):",
        applyNow: "Apply Now",
        applicationSentTitle: "Application Sent",
        applicationSentDesc: "Your application for the following job has been sent:",
        close: "Close",
    },
    nso: {
      logo: "Ntirho",
      language: "Sepedi",
      languageOptionSepedi: "Sepedi",
      languageOptionEnglish: "Seisimane",
      signUp: "Ingwadiša",
      logIn: "Kena",
      logOut: "Tšwa",
      heroTitle: "Hwetša Mešomo Kgauswi le Wena",
      thaboStoryTitle: "Kanegelo ya Thabo",
      thaboStory: "Akanya ka Thabo, moithuti yo a sa tšwago go aloga go tšwa motsaneng o monnyane, yo a hwetšago gore diphaphatha tša go nyaka mošomo tša setlwaedi di sa mo swanele, gomme a šala a se na menyetla.",
      footerContact: "Ikgokaganye le rena",
      footerPrivacy: "Leano la Bohlokwa bja Tshedimosetso",
      footerTraining: "Methopo ya Thuto",
      footerRights: "Ntirho. Ditokelo ka moka di bolokilwe.",
      postJobTitle: "Romela Mošomo o Moswa",
      jobTitleLabel: "Leina la Mošomo",
      jobTitlePlaceholder: "mohl., Mošomi wa Kakaretšo",
      companyLabel: "Khamphani",
      companyPlaceholder: "mohl., BuildIt Polokwane",
      locationLabel: "Lefelo goba Mošomo",
      locationPlaceholder: "mohlala: Polokwane goba Mošomi wa di-Computer",
      descriptionLabel: "Tlhalošo ya Mošomo",
      descriptionPlaceholder: "Hlalosa maikarabelo le dinyakwa tša mošomo.",
      skillsLabel: "Mabokgoni a Hlokagalago",
      skillsPlaceholder: "Kgetha mabokgoni a hlokagalago",
      skillsDescription: "Kgetha mabokgoni ka moka a hlokagalago bakeng sa mošomo wo.",
      skillsDescriptionProfile: "Kgetha mabokgoni ka moka ao a go swanelago.",
      postJobButton: "Romela Mošomo",
      postJobFooterLink: "Romela Mošomo",
      browseJobsTitle: "Bona Menyetla ya Mešomo",
      browseJobsSubtitle: "Hwetša mošomo wo o sepelelanago le bokgoni bja gago lefelong la geno.",
      filterBySkillPlaceholder: "Hlotla ka bokgoni",
      allSkills: "Mabokgoni Ka moka",
      clearFilters: "Hlakola Dihlotsi",
      noJobsFoundTitle: "Ga go Mešomo ye e Fumanwego",
      noJobsFoundSubtitle: "Lokiša dihlotsi tša gago go bona menyetla ye mentši.",
      viewDetails: "Lebelela Dintlha",
      yourJobMatchesTitle: "Mešomo ye e Go Swanelago",
      welcomeBack: "O Amogetšwe Gape",
      yourJobMatchesSubtitle: "Mešomo ye e go swanelago ke ye.",
      findingJobsLoading: "Re nyaka mešomo ye kaone go wena...",
      errorOccurredTitle: "Go Diregile Phošo",
      tryAgain: "Leka Gape",
      noMatchesFoundTitle: "Ga go Tšhwanetšo ye e Fumanwego",
      noMatchesFoundSubtitle: "Ga re kgone go hwetša mešomo ye e swanelago bokgoni bja gago gabjale. Leka go mpshafatša profaele ya gago.",
      matchScore: "Palo ya Tšhwanetšo",
      matchedSkills: "Mabokgoni a Tšhwanetšo",
      editProfile: "Lokiša Profaele",
      editProfileTitle: "Lokiša Profaele ya Gago",
      editProfileDescription: "Dira diphetogo profaeleng ya gago fa. Tobetsa 'Boloka' ge o feditše.",
      mySkills: "Mabokgoni a ka",
      myInterests: "Dithahasello tša ka",
      createAccountTitle: "Hlama Akhaonto ya Gago",
      myAccount: "Akhaonto ya ka",
      profile: "Profaele",
      myMatches: "Tšhwanetšo ya ka",
      findAJob: "Hwetša Mošomo",
      jobPostedSuccessTitle: "Mošomo o Rometswe ka Katlego",
      jobPostedSuccessDesc: "Mošomo o moswa o tsentšwe mananeong.",
      jobPostedErrorTitle: "Go Romela go Paletswe",
      jobPostedErrorDesc: "Go bile le phošo ge o be o romela mošomo. Leka gape.",
      searchSkillsPlaceholder: "Nyakišiša mabokgoni...",
      noSkillsFound: "Ga go na mabokgoni a fumanwego.",
      magicLinkSentTitle: "Khokagano ya Maselamose e Rometswe!",
      magicLinkSentDesc: "O tsena go akhaonto ya gago.",
      loginSuccessTitle: "O Kene ka Katlego",
      loginFailedTitle: "Go Kena go Paletswe",
      loginFailedDesc: "Re paletšwe go romela khokagano ya maselamose. Leka gape.",
      magicLinkPrompt: "Tsenya imeile ya gago go amogela khokagano ya maselamose.",
      emailPlaceholder: "Tsenya imeile ya gago",
      sendMagicLink: "Romela Khokagano",
      profileUpdateSuccessTitle: "Profaele e Mpshafaditšwe",
      profileUpdateSuccessDesc: "Diphetogo tša gago di bolokilwe ka katlego.",
      profileUpdateErrorTitle: "Go Mpshafatša go Paletswe",
      profileUpdateErrorDesc: "Go bile le phošo ge o be o mpshafatša profaele ya gago. Leka gape.",
      nameLabel: "Leina",
      namePlaceholder: "Tsenya leina la gago",
      saveChanges: "Boloka Diphetogo",
      registrationSuccessTitle: "O Ingwadišitše ka Katlego",
      registrationSuccessDesc: "Akhaonto ya gago e hlodilwe.",
      registrationFailedTitle: "Go Ingwadiša go Paletswe",
      registrationFailedDesc: "Go bile le phošo nakong ya go ingwadiša. Leka gape.",
      emailLabel: "Imeile",
      submit: "Romela",
      voiceSearchListening: "E theeletša...",
      voiceSearchSpeakNow: "Bolela gona bjale go nyaka ka lentšu.",
      voiceSearchComplete: "Nyakišišo e Feditše!",
      voiceSearchProcessed: "Nyakišišo ya lentšu e šetšwe.",
      voiceSearchFailed: "Go Nyaka ka Lentšu go Paletswe",
      voiceSearchFailedDesc: "Re paletšwe go šoma lentšu la gago. Leka gape.",
      voiceSearchTitle: "Nyaka ka Lentšu",
      voiceSearchDescription: "Ga o kgone go thaepa? Ga go bothata. Tobetsa konopo o re botše mošomo wo o nyakago ka Sepedi.",
      youSaidSepedi: "O rile (Sepedi):",
      weUnderstoodEnglish: "Re kwešišitše (Seisimane):",
      applyNow: "Romela Kopo Gona Bjale",
      applicationSentTitle: "Kopo e Rometswe",
      applicationSentDesc: "Kopo ya gago ya mošomo o latelago e rometswe:",
      close: "Tswalela",
  },
  ts: {
    logo: "Ntirho",
      language: "Sepedi",
      languageOptionSepedi: "Sepedi",
      languageOptionEnglish: "Seisimane",
      signUp: "Ingwadiša",
      logIn: "Kena",
      logOut: "Tšwa",
      heroTitle: "Hwetša Mešomo Kgauswi le Wena",
      thaboStoryTitle: "Kanegelo ya Thabo",
      thaboStory: "Akanya ka Thabo, moithuti yo a sa tšwago go aloga go tšwa motsaneng o monnyane, yo a hwetšago gore diphaphatha tša go nyaka mošomo tša setlwaedi di sa mo swanele, gomme a šala a se na menyetla.",
      footerContact: "Ikgokaganye le rena",
      footerPrivacy: "Leano la Bohlokwa bja Tshedimosetso",
      footerTraining: "Methopo ya Thuto",
      footerRights: "Ntirho. Ditokelo ka moka di bolokilwe.",
      postJobTitle: "Romela Mošomo o Moswa",
      jobTitleLabel: "Leina la Mošomo",
      jobTitlePlaceholder: "mohl., Mošomi wa Kakaretšo",
      companyLabel: "Khamphani",
      companyPlaceholder: "mohl., BuildIt Polokwane",
      locationLabel: "Lefelo goba Mošomo",
      locationPlaceholder: "mohlala: Polokwane goba Mošomi wa di-Computer",
      descriptionLabel: "Tlhalošo ya Mošomo",
      descriptionPlaceholder: "Hlalosa maikarabelo le dinyakwa tša mošomo.",
      skillsLabel: "Mabokgoni a Hlokagalago",
      skillsPlaceholder: "Kgetha mabokgoni a hlokagalago",
      skillsDescription: "Kgetha mabokgoni ka moka a hlokagalago bakeng sa mošomo wo.",
      skillsDescriptionProfile: "Kgetha mabokgoni ka moka ao a go swanelago.",
      postJobButton: "Romela Mošomo",
      postJobFooterLink: "Romela Mošomo",
      browseJobsTitle: "Bona Menyetla ya Mešomo",
      browseJobsSubtitle: "Hwetša mošomo wo o sepelelanago le bokgoni bja gago lefelong la geno.",
      filterBySkillPlaceholder: "Hlotla ka bokgoni",
      allSkills: "Mabokgoni Ka moka",
      clearFilters: "Hlakola Dihlotsi",
      noJobsFoundTitle: "Ga go Mešomo ye e Fumanwego",
      noJobsFoundSubtitle: "Lokiša dihlotsi tša gago go bona menyetla ye mentši.",
      viewDetails: "Lebelela Dintlha",
      yourJobMatchesTitle: "Mešomo ye e Go Swanelago",
      welcomeBack: "O Amogetšwe Gape",
      yourJobMatchesSubtitle: "Mešomo ye e go swanelago ke ye.",
      findingJobsLoading: "Re nyaka mešomo ye kaone go wena...",
      errorOccurredTitle: "Go Diregile Phošo",
      tryAgain: "Leka Gape",
      noMatchesFoundTitle: "Ga go Tšhwanetšo ye e Fumanwego",
      noMatchesFoundSubtitle: "Ga re kgone go hwetša mešomo ye e swanelago bokgoni bja gago gabjale. Leka go mpshafatša profaele ya gago.",
      matchScore: "Palo ya Tšhwanetšo",
      matchedSkills: "Mabokgoni a Tšhwanetšo",
      editProfile: "Lokiša Profaele",
      editProfileTitle: "Lokiša Profaele ya Gago",
      editProfileDescription: "Dira diphetogo profaeleng ya gago fa. Tobetsa 'Boloka' ge o feditše.",
      mySkills: "Mabokgoni a ka",
      myInterests: "Dithahasello tša ka",
      createAccountTitle: "Hlama Akhaonto ya Gago",
      myAccount: "Akhaonto ya ka",
      profile: "Profaele",
      myMatches: "Tšhwanetšo ya ka",
      findAJob: "Hwetša Mošomo",
      jobPostedSuccessTitle: "Mošomo o Rometswe ka Katlego",
      jobPostedSuccessDesc: "Mošomo o moswa o tsentšwe mananeong.",
      jobPostedErrorTitle: "Go Romela go Paletswe",
      jobPostedErrorDesc: "Go bile le phošo ge o be o romela mošomo. Leka gape.",
      searchSkillsPlaceholder: "Nyakišiša mabokgoni...",
      noSkillsFound: "Ga go na mabokgoni a fumanwego.",
      magicLinkSentTitle: "Khokagano ya Maselamose e Rometswe!",
      magicLinkSentDesc: "O tsena go akhaonto ya gago.",
      loginSuccessTitle: "O Kene ka Katlego",
      loginFailedTitle: "Go Kena go Paletswe",
      loginFailedDesc: "Re paletšwe go romela khokagano ya maselamose. Leka gape.",
      magicLinkPrompt: "Tsenya imeile ya gago go amogela khokagano ya maselamose.",
      emailPlaceholder: "Tsenya imeile ya gago",
      sendMagicLink: "Romela Khokagano",
      profileUpdateSuccessTitle: "Profaele e Mpshafaditšwe",
      profileUpdateSuccessDesc: "Diphetogo tša gago di bolokilwe ka katlego.",
      profileUpdateErrorTitle: "Go Mpshafatša go Paletswe",
      profileUpdateErrorDesc: "Go bile le phošo ge o be o mpshafatša profaele ya gago. Leka gape.",
      nameLabel: "Leina",
      namePlaceholder: "Tsenya leina la gago",
      saveChanges: "Boloka Diphetogo",
      registrationSuccessTitle: "O Ingwadišitše ka Katlego",
      registrationSuccessDesc: "Akhaonto ya gago e hlodilwe.",
      registrationFailedTitle: "Go Ingwadiša go Paletswe",
      registrationFailedDesc: "Go bile le phošo nakong ya go ingwadiša. Leka gape.",
      emailLabel: "Imeile",
      submit: "Romela",
      voiceSearchListening: "E theeletša...",
      voiceSearchSpeakNow: "Bolela gona bjale go nyaka ka lentšu.",
      voiceSearchComplete: "Nyakišišo e Feditše!",
      voiceSearchProcessed: "Nyakišišo ya lentšu e šetšwe.",
      voiceSearchFailed: "Go Nyaka ka Lentšu go Paletswe",
      voiceSearchFailedDesc: "Re paletšwe go šoma lentšu la gago. Leka gape.",
      voiceSearchTitle: "Nyaka ka Lentšu",
      voiceSearchDescription: "Ga o kgone go thaepa? Ga go bothata. Tobetsa konopo o re botše mošomo wo o nyakago ka Sepedi.",
      youSaidSepedi: "O rile (Sepedi):",
      weUnderstoodEnglish: "Re kwešišitše (Seisimane):",
      applyNow: "Romela Kopo Gona Bjale",
      applicationSentTitle: "Kopo e Rometswe",
      applicationSentDesc: "Kopo ya gago ya mošomo o latelago e rometswe:",
      close: "Tswalela",
  }

};

export type Translations = typeof translations.en;

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private languageSubject = new BehaviorSubject<Language>('en');
  language$ = this.languageSubject.asObservable();
  
  get language(): Language {
    return this.languageSubject.value;
  }

  get translations(): Translations {
    return translations[this.language];
  }

  setLanguage(lang: Language): void {
    this.languageSubject.next(lang);

    // Save to the local storage
    localStorage.setItem("language", lang);
  }

  getLang(): string{
    return localStorage.getItem("language") ?? 'en';
  }

  getLanguage(): Language{
    const val = localStorage.getItem("language");

    if (val === 'nso')
      return 'nso';
    if (val === 'ts')
      return 'ts';

    return 'en';
  }


}

