export const Translation = {
    en: {
        logo: "Mogwebi",
        language: "English",
        languageOptionSepedi: "Sepedi",
        languageOptionEnglish: "English",
        signUp: "Sign Up",
        logIn: "Log In",
        logOut: "Log Out",
        heroTitle: "Find Jobs Near You",
        thaboStoryTitle: "Thabo's Story",
        thaboStory: "Consider Thabo, a recent graduate from a small village who finds that traditional platforms like LinkedIn aren’t tailored to his local context, leaving him with few opportunities.",
        footerContact: "Contact Us",
        footerPrivacy: "Privacy Policy",
        footerTraining: "Training Resources",
        footerRights: "© 2024 Mogwebi. All rights reserved.",
        postJobTitle: "Post a New Job",
        jobTitleLabel: "Job Title",
        jobTitlePlaceholder: "e.g., General Worker",
        companyLabel: "Company",
        companyPlaceholder: "e.g., BuildIt Polokwane",
        locationLabel: "Location",
        locationPlaceholder: "e.g., Polokwane",
        descriptionLabel: "Job Description",
        descriptionPlaceholder: "Describe the job responsibilities and requirements.",
        skillsLabel: "Required Skills",
        skillsPlaceholder: "Select required skills",
        skillsDescription: "Select all skills required for this job.",
        skillsDescriptionProfile: "Select all skills that apply to you.",
        postJobButton: "Post Job",
        postJobFooterLink: "Post a Job",
        browseJobsTitle: "Browse Job Opportunities",
        browseJobsSubtitle: "Find work that matches your skills in your area.",
        filterBySkillPlaceholder: "Filter by skill",
        allSkills: "All Skills",
        clearFilters: "Clear Filters",
        noJobsFoundTitle: "No Jobs Found",
        noJobsFoundSubtitle: "Try adjusting your filters to find more opportunities.",
        viewDetails: "View Details",
        yourJobMatchesTitle: "Your Job Matches",
        welcomeBack: "Welcome back",
        yourJobMatchesSubtitle: "Here are jobs tailored for you.",
        findingJobsLoading: "Finding the best jobs for you...",
        errorOccurredTitle: "An Error Occurred",
        tryAgain: "Try Again",
        noMatchesFoundTitle: "No Matches Found",
        noMatchesFoundSubtitle: "We couldn't find any jobs matching your skills right now. Try updating your profile.",
        matchScore: "Match Score",
        matchedSkills: "Matched Skills",
        editProfile: "Edit Profile",
        editProfileTitle: "Edit Your Profile",
        editProfileDescription: "Make changes to your profile here. Click save when you're done.",
        mySkills: "My Skills",
        myInterests: "My Interests",
        createAccountTitle: "Create Your Account",
        myAccount: "My Account",
        profile: "Profile",
        myMatches: "My Matches",
        findAJob: "Find a Job",
        jobPostedSuccessTitle: "Job Posted Successfully",
        jobPostedSuccessDesc: "The new job has been added to the listings.",
        jobPostedErrorTitle: "Posting Failed",
        jobPostedErrorDesc: "An error occurred while posting the job. Please try again.",
        searchSkillsPlaceholder: "Search skills...",
        noSkillsFound: "No skills found.",
        magicLinkSentTitle: "Magic Link Sent!",
        magicLinkSentDesc: "You are now being logged in.",
        loginSuccessTitle: "Login Successful",
        loginFailedTitle: "Login Failed",
        loginFailedDesc: "Could not send magic link. Please try again.",
        magicLinkPrompt: "Enter your email to receive a magic link to sign in.",
        emailPlaceholder: "Enter your email",
        sendMagicLink: "Send Magic Link",
        profileUpdateSuccessTitle: "Profile Updated",
        profileUpdateSuccessDesc: "Your changes have been saved successfully.",
        profileUpdateErrorTitle: "Update Failed",
        profileUpdateErrorDesc: "An error occurred while updating your profile. Please try again.",
        nameLabel: "Name",
        namePlaceholder: "Enter your name",
        saveChanges: "Save Changes",
        registrationSuccessTitle: "Registration Successful",
        registrationSuccessDesc: "Your account has been created.",
        registrationFailedTitle: "Registration Failed",
        registrationFailedDesc: "An error occurred during registration. Please try again.",
        emailLabel: "Email",
        submit: "Submit",
        voiceSearchListening: "Listening...",
        voiceSearchSpeakNow: "Speak now to search with your voice.",
        voiceSearchComplete: "Search Complete!",
        voiceSearchProcessed: "Your voice search has been processed.",
        voiceSearchFailed: "Voice Search Failed",
        voiceSearchFailedDesc: "Could not process your voice input. Please try again.",
        voiceSearchTitle: "Search with your voice",
        voiceSearchDescription: "Can't type? No problem. Press the button and tell us what job you're looking for in Sepedi.",
        youSaidSepedi: "You said (Sepedi):",
        weUnderstoodEnglish: "We understood (English):",
        applyNow: "Apply Now",
        applicationSentTitle: "Application Sent",
        applicationSentDesc: "Your application for the following job has been sent:",
        close: "Close",
    },
    se: {
        logo: "Mogwebi",
        language: "Sepedi",
        languageOptionSepedi: "Sepedi",
        languageOptionEnglish: "English",
        signUp: "Ingwadiše",
        logIn: "Tsena",
        logOut: "Tšwa",
        heroTitle: "Hwetša Mešomo Kgauswi le Wena",
        thaboStoryTitle: "Kanegelo ya Thabo",
        thaboStory: "Akanya ka Thabo, moithuti yo a sa tšwago go aloga go tšwa motsaneng o monnyane yo a hwetšago gore mananeo a tlwaelegilego a go swana le LinkedIn ga se a mo lokela, a mo tlogela a na le menyetla e menyenyane.",
        footerContact: "Ikgokaganye le rena",
        footerPrivacy: "Pholisi ya Sephiri",
        footerTraining: "Methopo ya Tlhahlo",
        footerRights: "© 2024 Mogwebi. Ditokelo ka moka di lotilwe.",
        postJobTitle: "Romela Mošomo o Mofsa",
        jobTitleLabel: "Thaetlele ya Mošomo",
        jobTitlePlaceholder: "mohl., Mošomi wa Kakaretšo",
        companyLabel: "Khamphani",
        companyPlaceholder: "mohl., BuildIt Polokwane",
        locationLabel: "Lefelo",
        locationPlaceholder: "mohl., Polokwane",
        descriptionLabel: "Tlhalošo ya Mošomo",
        descriptionPlaceholder: "Hlalosa maikarabelo le dinyakwa tša mošomo.",
        skillsLabel: "Mabokgoni a a Hlokegago",
        skillsPlaceholder: "Kgetha mabokgoni a a hlokegago",
        skillsDescription: "Kgetha mabokgoni ka moka a hlokegago bakeng sa mošomo wo.",
        skillsDescriptionProfile: "Kgetha mabokgoni ka moka ao a go šomelago.",
        postJobButton: "Romela Mošomo",
        postJobFooterLink: "Romela Mošomo",
        browseJobsTitle: "Brousa menyetla ya mešomo",
        browseJobsSubtitle: "Hwetša mošomo wo o sepelelanago le mabokgoni a gago lefelong la geno.",
        filterBySkillPlaceholder: "Hlotla ka bokgoni",
        allSkills: "Mabokgoni Ka moka",
        clearFilters: "Hlakola Dihlodi",
        noJobsFoundTitle: "Ga go Mešomo ye e Hweditšwego",
        noJobsFoundSubtitle: "Leka go lokiša dihlotli tša gago go hwetša menyetla e mentši.",
        viewDetails: "Lebelela Dintlha",
        yourJobMatchesTitle: "Mešomo ya Gago ye e Tšhwanelago",
        welcomeBack: "O amogetšwe gape",
        yourJobMatchesSubtitle: "Ye ke mešomo yeo e go loketšego.",
        findingJobsLoading: "E hwetša mešomo ye kaone go wena...",
        errorOccurredTitle: "Go na le Phošo ye e Diregilego",
        tryAgain: "Leka Gape",
        noMatchesFoundTitle: "Ga go Ditiragalo tše di Hweditšwego",
        noMatchesFoundSubtitle: "Ga se ra kgona go hwetša mešomo ye e sepelelanago le mabokgoni a gago gabjale. Leka go mpshafatša phrofayele ya gago.",
        matchScore: "Dintlha tša go Tšhwanela",
        matchedSkills: "Mabokgoni a go Tšhwanelana",
        editProfile: "Lokiša Profaele",
        editProfileTitle: "Lokiša Profaele ya Gago",
        editProfileDescription: "Dira diphetogo profaeleng ya gago fa. Tobetsa boloka ge o feditše.",
        mySkills: "Mabokgoni a ka",
        myInterests: "Dilo tšeo ke di Thabelago",
        createAccountTitle: "Hlama Akhaonto ya Gago",
        myAccount: "Akhaonto ya ka",
        profile: "Profaele",
        myMatches: "Mešomo yaka",
        findAJob: "Hwetša Mošomo",
        jobPostedSuccessTitle: "Mošomo o Rometswe ka Katleho",
        jobPostedSuccessDesc: "Mošomo o mofsa o okeleditswe mananeong.",
        jobPostedErrorTitle: "Go Romela go Paletswe",
        jobPostedErrorDesc: "Go bile le phoso ge o be o romela mošomo. Hle leka gape.",
        searchSkillsPlaceholder: "Nyakisisa mabokgoni...",
        noSkillsFound: "Ga go na mabokgoni a hwetswego.",
        magicLinkSentTitle: "Khokagano ya Maselamose e Rometswe!",
        magicLinkSentDesc: "O tsena go akhaonto ya gago.",
        loginSuccessTitle: "O Tsenye ka Katlego",
        loginFailedTitle: "Go Tsena go Paletswe",
        loginFailedDesc: "A re kgone go romela khokagano ya maselamose. Hle leka gape.",
        magicLinkPrompt: "Tsenya imeile ya gago go amogela khokagano ya maselamose go tsena.",
        emailPlaceholder: "Tsenya imeile ya gago",
        sendMagicLink: "Romela Khokagano ya Maselamose",
        profileUpdateSuccessTitle: "Profaele e Mpshafatswe",
        profileUpdateSuccessDesc: "Diphetogo tša gago di bolokilwe ka katlego.",
        profileUpdateErrorTitle: "Go Mpshafatša go Paletswe",
        profileUpdateErrorDesc: "Go bile le phošo ge o be o mpshafatša profaele ya gago. Hle leka gape.",
        nameLabel: "Leina",
        namePlaceholder: "Tsenya leina la gago",
        saveChanges: "Boloka Diphetogo",
        registrationSuccessTitle: "O Ingwadisitse ka Katlego",
        registrationSuccessDesc: "Akhaonto ya gago e hlotšwe.",
        registrationFailedTitle: "Go Ingwadisa go Paletswe",
        registrationFailedDesc: "Go bile le phoso nakong ya go ingwadisa. Hle leka gape.",
        emailLabel: "Imeile",
        submit: "Romela",
        voiceSearchListening: "E theeletse...",
        voiceSearchSpeakNow: "Bolela gona bjale go nyaka ka lentšu la gago.",
        voiceSearchComplete: "Nyakisiso e Feletse!",
        voiceSearchProcessed: "Nyakisiso ya gago ya lentšu e šetswe.",
        voiceSearchFailed: "Go Nyaka ka Lentšu go Paletswe",
        voiceSearchFailedDesc: "A re kgone go šoma lentšu la gago. Hle leka gape.",
        voiceSearchTitle: "Nyaka ka lentšu la gago",
        voiceSearchDescription: "Ga o kgone go thaepa? Ga go bothata. Tobetsa konopo o re botše gore o nyaka mošomo ofe ka Sepedi.",
        youSaidSepedi: "O rile (Sepedi):",
        weUnderstoodEnglish: "Re kwešišitše (Seisimane):",
        applyNow: "Dira Kopo Gona Bjale",
        applicationSentTitle: "Kopo e Rometswe",
        applicationSentDesc: "Kopo ya gago ya mošomo o latelago e rometswe:",
        close: "Tswalela",
    }
};
